### ISSUE TITLE
certificate files location

### ISSUE THREAD

**Issue by Dmitry1987** [andrewrothstein/ansible-consul-cluster#8]
Hi, thanks for the nice playbook!
I don't understand where to place my cert files for it to copy to servers?
Do I need to create the pki folder first myself on the servers, and place the crt/key files in it, and then point to them in the variables?

**Comment by andrewrothstein** [comment]
you're welcome! glad to hear that you find it useful!

the certs and keys for all of the hosts in your inventory should be in a single directory and then conveyed to the role with the role var `consul_agent_pki_dir`. for example

```
drew@headnode ~/mypki > ls -l core*.pem
-rw-------  1 drew  staff  1679 Feb 10 23:10 core-0001.mydomain.org-key.pem
-rw-r--r--  1 drew  staff  1444 Feb 10 23:10 core-0001.mydomain.org.pem
-rw-------  1 drew  staff  1679 Feb 10 23:10 core-0002.mydomain.org-key.pem
-rw-r--r--  1 drew  staff  1444 Feb 10 23:10 core-0002.mydomain.org.pem
-rw-------  1 drew  staff  1679 Feb 10 23:10 core-0003.mydomain.org-key.pem
-rw-r--r--  1 drew  staff  1444 Feb 10 23:10 core-0003.mydomain.org.pem
```

**Comment by MrTango** [comment]
Would be nice to have some lines how to setup and use the cert files in the readme.

**Comment by andrewrothstein** [comment]
Managing a PKI is a non-trivial undertaking. My roles that consume a PKI expect the keys/certs to be laid out on the file system per my [andrewrothstein.pki](http://github.com/andrewrothstein/ansible-pki) role. Always happy to accept a PR for improving the documentation.
